  name: Docker Up - Node

  on: [push]

  jobs: 
    push_to_registry: 
      name: Setup Docker Image
      runs-on: ubuntu-latest

      steps: 
        - name: checkout repository
          uses: actions/checkout@v2
        
        - name: Log in into docker hub
          uses: docker/login-action@v1
          with: 
            username: ${{ SECRETS.USERNAME }}
            password: ${{ SECRETS.PASSWORD }}
        
        - name: Send image to Docker hub
          working-directory: ./
          run: |
            docker build -t test2node
            docker push test2node